---
title: "Model Selection"
author: "Jack Krebsbach"
date: "1/28/2022"
output: html_document
---

## Load Libraries
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir=normalizePath("..")) #set working directory to the project directory
library(tidyverse)
library(tidymodels)
library(ranger)
library(randomForest)
library(RStoolbox)
library(sf)
```


## Source Files and build classifier model
```{r, echo=FALSE, results=FALSE, message=FALSE, include=FALSE }
source('./code/helpers/classify_helpers.R')
show_engines("rand_forest")
rf_pixel_model <- rand_forest() %>%
                  set_engine("ranger", importance = "impurity") %>%
                  set_mode("classification") %>%
                  translate()
```

## Load training and validation set

```{r}
full_train <- readRDS('./clean_data/rdata/pixel_values/training_set.rds')
full_val <- readRDS('./clean_data/rdata/pixel_values/validation_set.rds')
```


## Take 50,000 pixels per class from the training set

```{r}
set.seed(8765309)
train <- full_train %>%
  group_by(label) %>%
  slice_sample(n = 50000) %>% # n is the number of pixels per polygon that we want to sample
  ungroup()
val <- full_val
```










