---
title: "Demonstration: Extracting features from ground-based photographs"
author: "Jack Krebsbach"
date: "4/25/2021"
output: html_document
---

## Setup
```{r setup}
#Make sure the working directory is correct
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## Import code library
```{r, include = FALSE, echo = FALSE}
#Libraries
library(tidyverse) 
library(magick)
library(imager)
library(reticulate)

#Python Environment and Script Sourcing
Sys.setenv(RETICULATE_PYTHON = '/Users/krebsbach/pyenvs/reticulate/bin/python3')
source_python("code/extracting_features/library/meanshift_segmentation.py")

#Texture Calcuation
source("code/extracting_features/library/glcm_texture.R")

#Color Space Transformations
source("code/extracting_features/library/color_space_transformation.R")
```

## Plot RGB Image
```{r}
rgb_file <-"outputs/demonstration/rgb.tif" 

rgb_file %>%
    raster::brick() %>%
    raster::plotRGB()
```

## Transform RGB image to HSV representation and plot HSV image
```{r}
hsv_file <- rgb_file %>% 
            color_transform(transform = "RGBtoHSV") 
hsv_file %>%
           raster::brick() %>%
           raster::plotRGB()
```

## Calculate texture and plot texture image
```{r}
hsv_file  %>%
    calculate_texture() %>%
    raster::brick() %>%
    raster::plotRGB()
```


## Apply meanshift image segmentation and plot segmented image
```{r}
hsv_file %>%
    segment() %>%  #Python function for image segmentation
    raster::brick() %>%
    raster::plotRGB()
```






